baseurl: /Blog
markdown: rdiscount
highlighter: pygments
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
#pname: Blog
title: Aurora's Blog
description: 一个懒惰的程序员，一个热爱生活的人。
email: aurora (at) aurorawu (dot) com
feed: /atom.xml

#菜单配置
nav:
  - text: Home 
    url: /Blog/index.html
  - text: Archives
    url: /Blog/archives.html
#  - text: Reading
#    url: /Blog/books.html
  - text: About
    url: /Blog/contact.html

#主题配置
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-weibo
    url: http://weibo.com/aurorawu91
  - class: fa-twitter
    url: https://twitter.com/aurorawu91

#评论信息
disqus:
  config: true 
  id: disqus_4BwlSmNnTj

duoshuo:
  config: false
  id: zhanxin
